// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMQu7KhwLBTbPv5qHH3ojUYQAsJpd2hUo',
    appId: '1:1095235233200:web:f3207fc14cf40b8a1ce275',
    messagingSenderId: '1095235233200',
    projectId: 'eve-test-81192',
    authDomain: 'eve-test-81192.firebaseapp.com',
    storageBucket: 'eve-test-81192.appspot.com',
    measurementId: 'G-16XX4MYEZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbGrs8AotcGceu84XPCVN2JivKdbm6a6M',
    appId: '1:1095235233200:android:37cb8d28e4ca1f031ce275',
    messagingSenderId: '1095235233200',
    projectId: 'eve-test-81192',
    storageBucket: 'eve-test-81192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNYLTjEg14pfLyg6IOFCMzDiDBImm_yo8',
    appId: '1:1095235233200:ios:dd5f3828c23624461ce275',
    messagingSenderId: '1095235233200',
    projectId: 'eve-test-81192',
    storageBucket: 'eve-test-81192.appspot.com',
    iosBundleId: 'com.example.eveTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNYLTjEg14pfLyg6IOFCMzDiDBImm_yo8',
    appId: '1:1095235233200:ios:3bc10a54db1d48b11ce275',
    messagingSenderId: '1095235233200',
    projectId: 'eve-test-81192',
    storageBucket: 'eve-test-81192.appspot.com',
    iosBundleId: 'com.example.eveTest.RunnerTests',
  );
}
